---
# yamllint disable rule:line-length
AWSTemplateFormatVersion: "2010-09-09"

Description: |
  ECR repository stack to host the custom adot-collector images.

Resources:
  AMPXRayRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: amp-xray-adot-collector
      ImageScanningConfiguration:
        ScanOnPush: "true"
  AMPXRayPromRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: amp-xray-prom-adot-collector
      ImageScanningConfiguration:
        ScanOnPush: "true"

Outputs:
  Arn:
    Value: !GetAtt Repository.Arn
