---
# yamllint disable rule:line-length
AWSTemplateFormatVersion: "2010-09-09"

Description: |
  ECR repository stack to host the custom adot-collector images.

Resources:
  AMPXRayRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: ecs-otel-amp-xray-collector
      ImageScanningConfiguration:
        ScanOnPush: "true"
  AMPXRayPromRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: ecs-otel-amp-xray-prom-collector
      ImageScanningConfiguration:
        ScanOnPush: "true"

Outputs:
  AMPXRayRepositoryArn:
    Value: !GetAtt AMPXRayRepository.Arn
  AMPXRayPromRepository:
    Value: !GetAtt AMPXRayPromRepository.Arn
